version: "3.8"
services:
  holder:
    build: ./BE/holder
    image: holder
    container_name: holder
    ports:
      - 8081:8081
    volumes:
      - ./BE/holder:/usr/src/app

  issuer:
    build: ./BE/issuer
    image: issuer
    container_name: issuer
    ports:
      - 8082:8082
    depends_on:
      - mysql-student
    volumes:
      - ./BE/issuer:/usr/src/app

  verifier:
    build: ./BE/verifier
    image: verifier
    container_name: verifier
    ports:
      - 8083:8083
    volumes:
      - ./BE/verifier:/usr/src/app

  service:
    build: ./BE/service
    image: service
    container_name: service
    ports:
<<<<<<< HEAD
      - "4000:4000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
=======
      - 4000:4000
    depends_on:
      - mysql-was
    volumes:
      - ./BE/service:/usr/src/app

  mysql-was:
    image: mysql:8.0
    container_name: mysql-was
>>>>>>> 4b9006879fd1399d99ee374d3863f97aff149b04
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_WAS_PASSWORD}
      MYSQL_DATABASE: db
<<<<<<< HEAD
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
=======
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql

  mysql-student:
    image: mysql:8.0
    container_name: mysql-student
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_STUDENT_PASSWORD}
      MYSQL_DATABASE: db
      TZ: Asia/Seoul
    volumes:
      - mysql-student-data:/var/lib/mysql

  service-homepage:
    build: ./FE/service-homepage
    image: service-homepage
    ports:
      - 3000:3000
    volumes:
      - ./FE/service-homepage:/usr/src/app

volumes:
  mysql-data:
  mysql-student-data:
>>>>>>> 4b9006879fd1399d99ee374d3863f97aff149b04
