version: "3.8"
services:
  holder:
    build: ./BE/holder
    image: holder
    container_name: holder
    ports:
      - 8081:8081
    depends_on:
      - mysql-was
    volumes:
      - ./BE/holder:/usr/src/app

  issuer:
    build: ./BE/issuer
    image: issuer
    container_name: issuer
    ports:
      - 8082:8082
    environment:
    # count 초기화를 원하면 "true", 아니면 "false"
      RESET_COUNTER: "false" 
    depends_on:
      - mysql-was
    volumes:
      - ./BE/issuer:/usr/src/app

  verifier:
    build: ./BE/verifier
    image: verifier
    container_name: verifier
    ports:
      - 8083:8083
    depends_on:
      - mysql-counter
    volumes:
      - ./BE/verifier:/usr/src/app

  service:
    build: ./BE/service
    image: service
    container_name: service
    ports:
      - 4000:4000
    depends_on:
      - mysql-was
    volumes:
      - ./BE/service:/usr/src/app

  mysql-was:
    image: mysql:8.0
    container_name: mysql-was
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_WAS_PASSWORD}
      MYSQL_DATABASE: db
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql

  mysql-counter:
    image: mysql:8.0
    container_name: mysql-counter
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_COUNTER_PASSWORD}
      MYSQL_DATABASE: db
      TZ: Asia/Seoul
    volumes:
      - mysql-counter-data:/var/lib/mysql

#  service-homepage:
#    build: ./FE/service-homepage
#    image: service-homepage
#    ports:
#      - 3000:3000
#    volumes:
#      - ./FE/service-homepage:/usr/src/app

volumes:
  mysql-data:
  mysql-counter-data:
