name: Auto Test (Service API only)

on:
  pull_request:
    branches: [main, dev]

jobs:
  auto-test:
    name: Run test codes
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Node 20.11
        uses: actions/setup-node@v2
        with:
          node-version: "20.11"

      # Holder
      - name: Install dependencies for Holder
        run: cd ./BE/holder && npm i

        - name: Set Environment Variables
        run: |
          echo "MAIL_USER=${{ secrets.MAIL_USER }}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> $GITHUB_ENV


      - name: Run test for Holder
        run: cd ./BE/holder && npm run test

      # Issuer
      - name: Install dependencies for Issuer
        run: cd ./BE/issuer && npm i

      - name: Run test for Holder
        run: cd ./BE/issuer && npm run test

      # Service
      - name: Install dependencies for Service
        run: cd ./BE/service && npm i

      - name: Run test for Service
        run: cd ./BE/service && npm run test

      # Verifier
      - name: Install dependencies for Verifier
        run: cd ./BE/verifier && npm i

      - name: Run test for Verifier
        run: cd ./BE/verifier && npm run test
